socket_path = "/tmp/test-signal-secmon.sock"
log_level = "info"

[[watches]]
path = "/tmp"
description = "Test watch for /tmp"
enabled = true

[[triggers]]
name = "test_trigger"
event_types = ["FileAccess"]
min_severity = "Low"
enabled = false
command = "echo"
args = ["Test trigger: {path}"]
run_async = true
cooldown_seconds = 1