name: Build and Cache

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: secmon-daemon
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Check flake
      run: nix flake check --show-trace

    - name: Build all packages
      run: |
        echo "Building secmon-daemon package..."
        nix build .#secmon-daemon --print-build-logs

        echo "Building default package..."
        nix build . --print-build-logs

    - name: Run tests (if available)
      run: |
        echo "Running tests in nix environment..."
        nix develop -c cargo test --verbose || echo "No tests found or tests failed"

    - name: Build development shell
      run: nix develop -c echo "Development shell built successfully"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: github.event_name == 'push'
      with:
        name: secmon-binaries
        path: |
          result/bin/secmon-daemon
          result/bin/secmon-client
          result/bin/secmon-msg
        retention-days: 30

  # Additional job for cross-platform builds if needed
  build-matrix:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-linux]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-platforms = aarch64-linux

    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: secmon-daemon
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build for ${{ matrix.system }}
      run: |
        nix build .#packages.${{ matrix.system }}.secmon-daemon --print-build-logs || echo "Build failed for ${{ matrix.system }}"
